export enum TemplateCategory {
  PRODUCTIVITY = "PRODUCTIVITY",
  LIFE_OS = "LIFE_OS",
  HABITS = "HABITS",
  KNOWLEDGE = "KNOWLEDGE",
  FINANCE = "FINANCE",
  HEALTH = "HEALTH",
  CREATIVE = "CREATIVE",
  PERSONAL = "PERSONAL",
}
